name: Code Quality

on:
  push:
    branches: ["feat/wanderlust-mandar", "main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Lint Backend
        run: |
          cd backend
          npm ci || npm install
          npm run lint --if-present

      - name: Lint Frontend
        run: |
          cd frontend
          npm ci || npm install
          npm run lint --if-present