# Goal: Push the images to DockerHub 
name: Docker Push

on: 
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push (${{ matrix.folders }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: 
        folders: ['backend', 'frontend']
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Setup [Login]
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.folders }}
          push: true
          # Updated tag to wanderlust
          tags: ${{ vars.DOCKERHUB_USERNAME }}/wanderlust-${{ matrix.folders }}:latest