name: Docker Security Scan

on:
  workflow_call:
  workflow_dispatch:

jobs:
  docker-scan-frontend:
    name: Scan Frontend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image
        run: |
          docker build -t wanderlust-frontend:latest ./frontend

      - name: Run Trivy Scanner on Frontend Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'wanderlust-frontend:latest'
          format: 'table'
          exit-code: '0' # Set to '0' so vulnerabilities don't fail the job, or '1' if you WANT to break the pipeline on CRITICAL
          ignore-unfixed: true
          scanners: 'vuln,secret'
          severity: 'CRITICAL'

  docker-scan-backend:
    name: Scan Backend Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Backend Docker Image
        run: |
          docker build -t wanderlust-backend:latest ./backend

      - name: Run Trivy Scanner on Backend Image
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'wanderlust-backend:latest'
          format: 'table'
          exit-code: '0' # Set to '0' so vulnerabilities don't fail the job, or '1' if you WANT to break the pipeline on CRITICAL
          ignore-unfixed: true
          scanners: 'vuln,secret'
          severity: 'CRITICAL'